services:
  motorsharks:
    build:
      context: .
      dockerfile: ServerNode/Dockerfile
    container_name: motorsharks
    ports:
      - "8080:8080"
    environment:
      MOTORSHARKS_DATA_DIR: "/app/data"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

